`ifndef BRANCH_VH
`define BRANCH_VH

`define BRANCH_OP_WIDTH 3

`define BRANCH_BEQ  `BRANCH_OP_WIDTH'd0
`define BRANCH_BNE  `BRANCH_OP_WIDTH'd1
`define BRANCH_BLT  `BRANCH_OP_WIDTH'd2
`define BRANCH_BGE  `BRANCH_OP_WIDTH'd3
`define BRANCH_BLTU `BRANCH_OP_WIDTH'd4
`define BRANCH_BGEU `BRANCH_OP_WIDTH'd5

`endif // BRANCH_VH