`ifndef CMP_VH
`define CMP_VH

`define BRANCH_OP_WIDTH 3

`define OPCODE_BRANCH 7'b1100011
`define OPCODE_JAL    7'b1101111
`define OPCODE_JALR   7'b1100111

`define BRANCH_FUNCT3_BEQ  3'b000
`define BRANCH_FUNCT3_BNE  3'b001
`define BRANCH_FUNCT3_BLT  3'b100
`define BRANCH_FUNCT3_BGE  3'b101
`define BRANCH_FUNCT3_BLTU 3'b110
`define BRANCH_FUNCT3_BGEU 3'b111

`define BRANCH_BEQ  `BRANCH_OP_WIDTH'd0
`define BRANCH_BNE  `BRANCH_OP_WIDTH'd1
`define BRANCH_BLT  `BRANCH_OP_WIDTH'd2
`define BRANCH_BGE  `BRANCH_OP_WIDTH'd3
`define BRANCH_BLTU `BRANCH_OP_WIDTH'd4
`define BRANCH_BGEU `BRANCH_OP_WIDTH'd5

`endif // CMP_VH